### ISSUE TITLE
Minimal api - autoryzacja przez role

### ISSUE THREAD

**Issue by TheKostek** [sulmar/sulmar-sgh-blazor#2]
Kończąc temat, bo nie podaliśmy przykładu :)

Trzeba dodać AuthorizationBuilder i stworzyć policy z rolami dostępu, następnie w RequireAuthorization podajemy nazwę tej policy i działa pięknie :)

builder.Services.AddAuthorizationBuilder()
  .AddPolicy("admin_policy", policy =>
        policy
            .RequireRole("admin"));

// na grupie też bez problemu łapie
app.MapGroup("/api/customers").MapCustmoers().RequireAuthorization("admin_policy");

**Comment by sulmar** [comment]
Dzięki! Dodałem do naszego projektu:
https://github.com/sulmar/sulmar-sgh-blazor/blob/e62ca8f46bbf69e51746eb255336eb0857e4041a/src/SGH.Shopper/SGH.Shopper.Api/Program.cs#L144
